"""many-to-many user_shop

Revision ID: 05840dd1d109
Revises: 54cb0f9e510e
Create Date: 2025-12-30 22:50:33.907481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05840dd1d109'
down_revision = '54cb0f9e510e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shop',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shop_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_shop_id'), type_='foreignkey')
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_shop_id'), 'shop', ['shop_id'], ['id'])

    op.drop_table('user_shop')
    # ### end Alembic commands ###
