"""added stock recieved date

Revision ID: 36b9f255062a
Revises: e3c20e904f53
Create Date: 2026-08-23 12:42:00.569727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b9f255062a'
down_revision = 'e3c20e904f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_received_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'date', name='unique_store_received_date_per_shop')
    )
    with op.batch_alter_table('cashless_transaction', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashless_transaction', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    op.drop_table('store_received_date')
    # ### end Alembic commands ###
