"""empty message

Revision ID: 53880a91fd49
Revises: 36b9f255062a
Create Date: 2026-08-23 12:44:14.289310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53880a91fd49'
down_revision = '36b9f255062a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_received_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'date', name='unique_stock_received_date_per_shop')
    )
    op.drop_table('store_received_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_received_date',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'date', name=op.f('unique_store_received_date_per_shop'))
    )
    op.drop_table('stock_received_date')
    # ### end Alembic commands ###
