"""added the shop_id relationship in users

Revision ID: 54cb0f9e510e
Revises: f0b6de18a1dc
Create Date: 2025-12-27 08:54:32.991322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cb0f9e510e'
down_revision = 'f0b6de18a1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_shop_id', 'shop', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_shop_id', type_='foreignkey')
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
