"""added paid with temporary nullable attribute

Revision ID: c2f15a8b1f4b
Revises: 25e25cbb60b5
Create Date: 2026-07-02 22:52:24.943854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f15a8b1f4b'
down_revision = '25e25cbb60b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
