"""empty message

Revision ID: d5510828d4a7
Revises: c2f15a8b1f4b
Create Date: 2026-07-02 23:06:11.034503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5510828d4a7'
down_revision = 'c2f15a8b1f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
