"""empty message

Revision ID: daf704f39622
Revises: 05840dd1d109
Create Date: 2026-01-05 05:55:05.354159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf704f39622'
down_revision = '05840dd1d109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_product_per_day', ['product_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.drop_constraint('unique_product_per_day', type_='unique')

    # ### end Alembic commands ###
