"""empty message

Revision ID: e3c20e904f53
Revises: 545c64f0b018
Create Date: 2026-08-22 23:22:47.687723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c20e904f53'
down_revision = '545c64f0b018'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('cashless_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashless_transaction', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
